Repository Aerodisk/openvair, pull requests merged in 2025-07, with the labels that each got.

#187 Добавление функционала снапшотов в модуль виртуальных машин
  openvair/alembic/versions/1_initial_revisions.py
  openvair/libs/libvirt/vm.py
  openvair/modules/virtual_machines/adapters/orm.py
  openvair/modules/virtual_machines/adapters/repository.py
  openvair/modules/virtual_machines/adapters/serializer.py
  openvair/modules/virtual_machines/config.py
  openvair/modules/virtual_machines/domain/base.py
  openvair/modules/virtual_machines/domain/exceptions.py
  openvair/modules/virtual_machines/domain/libvirt2/driver.py
  openvair/modules/virtual_machines/entrypoints/api.py
  openvair/modules/virtual_machines/entrypoints/crud.py
  openvair/modules/virtual_machines/entrypoints/schemas.py
  openvair/modules/virtual_machines/service_layer/exceptions.py
  openvair/modules/virtual_machines/service_layer/services.py
Labels: feature

#192 Реализация функционала клонирования ВМ
  openvair/libs/messaging/clients/rpc_clients/volume_rpc_client.py
  openvair/libs/messaging/service_interfaces/volume.py
  openvair/libs/qemu_img/adapter.py
  openvair/modules/event_store/entrypoints/crud.py
  openvair/modules/virtual_machines/domain/exceptions.py
  openvair/modules/virtual_machines/domain/libvirt2/driver.py
  openvair/modules/virtual_machines/entrypoints/api.py
  openvair/modules/virtual_machines/entrypoints/crud.py
  openvair/modules/virtual_machines/entrypoints/schemas.py
  openvair/modules/virtual_machines/libs/template_rendering/vm_renderer.py
  openvair/modules/virtual_machines/service_layer/exceptions.py
  openvair/modules/virtual_machines/service_layer/services.py
  openvair/modules/volume/adapters/dto/internal/commands.py
  openvair/modules/volume/adapters/dto/internal/models.py
  openvair/modules/volume/domain/base.py
  openvair/modules/volume/domain/physical_fs/localfs.py
  openvair/modules/volume/entrypoints/crud.py
  openvair/modules/volume/entrypoints/schemas.py
  openvair/modules/volume/service_layer/exceptions.py
  openvair/modules/volume/service_layer/services.py
Labels: volume, virtual_machine

#212 Рефакторинг Storage: перевод на новый UoW и обновление Repository
  openvair/modules/storage/adapters/orm.py
  openvair/modules/storage/adapters/repository.py
  openvair/modules/storage/service_layer/services.py
  openvair/modules/storage/service_layer/unit_of_work.py
Labels: refactoring

#220 Рефакторинг Network: перевод на новый UoW и обновление Repository
  openvair/modules/network/adapters/orm.py
  openvair/modules/network/adapters/repository.py
  openvair/modules/network/service_layer/exceptions.py
  openvair/modules/network/service_layer/services.py
  openvair/modules/network/service_layer/unit_of_work.py
Labels: refactoring

#227 Рефакторинг модуля Event_store
  openvair/modules/event_store/adapters/repository.py
  openvair/modules/event_store/adapters/repository2.py
  openvair/modules/event_store/entrypoints/crud.py
  openvair/modules/event_store/service_layer/services.py
  openvair/modules/event_store/service_layer/unit_of_work.py
  openvair/modules/event_store/service_layer/unit_of_work2.py
Labels: enhancement

#228 FIX: Virtual machines. Исправлена ошибка создания виртуального диска (Volume) при редактировании ВМ
  openvair/modules/virtual_machines/service_layer/services.py
Labels: fix, virtual_machine
