Repository Aerodisk/openvair, pull requests merged in 2025-02, with the labels that each got.

#101 Миграция модуля block_device на новую версию execute
  openvair/modules/block_device/domain/fibre_channel/fibre_channel.py
  openvair/modules/block_device/domain/iscsi/iscsi.py
  openvair/modules/block_device/domain/model.py
Labels: enhancement

#102 Миграция модуля `image` на новую версию execute
  openvair/modules/image/domain/physical_fs/localfs.py
  openvair/modules/image/domain/remotefs/nfs.py
Labels: enhancement

#108 Миграция модуля storage на новую версию execute
  openvair/modules/storage/adapters/parted.py
  openvair/modules/storage/domain/base.py
  openvair/modules/storage/domain/physical_fs/localfs.py
  openvair/modules/storage/domain/remotefs/nfs.py
Labels: enhancement

#99 Обновление функции validate_objects в связи с переходом на Pydantic v2
  openvair/modules/event_store/entrypoints/crud.py
  openvair/modules/storage/entrypoints/api.py
  openvair/modules/storage/entrypoints/crud.py
  openvair/modules/tools/utils.py
  openvair/modules/virtual_machines/entrypoints/crud.py
Labels: enhancement, pydantic, fix

#104 Добавление функционала удаления бекапа
  openvair/modules/backup/adapters/restic/restic.py
  openvair/modules/backup/domain/backupers/restic_backuper.py
  openvair/modules/backup/domain/base.py
  openvair/modules/backup/entrypoints/api.py
  openvair/modules/backup/entrypoints/crud.py
  openvair/modules/backup/schemas.py
  openvair/modules/backup/service_layer/services.py
Labels: feature

#114 Миграция модуля network на новую версию execute
  openvair/modules/network/domain/interfaces/physical.py
  openvair/modules/network/domain/interfaces/virtual.py
  openvair/modules/network/domain/utils/ip_manager.py
  openvair/modules/network/domain/utils/netplan_manager.py
  openvair/modules/network/domain/utils/ovs_manager.py
  openvair/modules/network/utils.py
Labels: enhancement

#123 Очистка легаси-кода tools
  openvair/modules/tools/utils.py
  openvair/modules/tools/validators.py
Labels: refactoring, libs
